from __future__ import annotations

GEOMETRY_KIND_TO_STRUCTURE = {
    "box": "single_box",
    "cylinder": "single_tubs",
    "sphere": "single_sphere",
    "orb": "single_orb",
    "cons": "single_cons",
    "trd": "single_trd",
    "polycone": "single_polycone",
    "cuttubs": "single_cuttubs",
    "trap": "single_trap",
    "para": "single_para",
    "torus": "single_torus",
    "ellipsoid": "single_ellipsoid",
    "elltube": "single_elltube",
    "polyhedra": "single_polyhedra",
}


SUPPORTED_GEOMETRY_KINDS = set(GEOMETRY_KIND_TO_STRUCTURE.keys())


GEOMETRY_SLOT_TARGET_TO_PATHS = {
    "geometry.kind": {"geometry.structure", "geometry.root_name"},
    "geometry.size_triplet_mm": {
        "geometry.params.module_x",
        "geometry.params.module_y",
        "geometry.params.module_z",
    },
    "geometry.radius_mm": {"geometry.params.child_rmax"},
    "geometry.half_length_mm": {"geometry.params.child_hz"},
    "geometry.radius1_mm": {"geometry.params.rmax1"},
    "geometry.radius2_mm": {"geometry.params.rmax2"},
    "geometry.x1_mm": {"geometry.params.x1"},
    "geometry.x2_mm": {"geometry.params.x2"},
    "geometry.y1_mm": {"geometry.params.y1"},
    "geometry.y2_mm": {"geometry.params.y2"},
    "geometry.z_mm": {"geometry.params.module_z"},
    "geometry.z_planes_mm": {
        "geometry.params.z1",
        "geometry.params.z2",
        "geometry.params.z3",
    },
    "geometry.radii_mm": {
        "geometry.params.r1",
        "geometry.params.r2",
        "geometry.params.r3",
    },
    "geometry.trap_x1_mm": {"geometry.params.trap_x1"},
    "geometry.trap_x2_mm": {"geometry.params.trap_x2"},
    "geometry.trap_x3_mm": {"geometry.params.trap_x3"},
    "geometry.trap_x4_mm": {"geometry.params.trap_x4"},
    "geometry.trap_y1_mm": {"geometry.params.trap_y1"},
    "geometry.trap_y2_mm": {"geometry.params.trap_y2"},
    "geometry.trap_z_mm": {"geometry.params.trap_z"},
    "geometry.para_x_mm": {"geometry.params.para_x"},
    "geometry.para_y_mm": {"geometry.params.para_y"},
    "geometry.para_z_mm": {"geometry.params.para_z"},
    "geometry.para_alpha_deg": {"geometry.params.para_alpha"},
    "geometry.para_theta_deg": {"geometry.params.para_theta"},
    "geometry.para_phi_deg": {"geometry.params.para_phi"},
    "geometry.torus_major_radius_mm": {"geometry.params.torus_rtor"},
    "geometry.torus_minor_radius_mm": {"geometry.params.torus_rmax"},
    "geometry.ellipsoid_ax_mm": {"geometry.params.ellipsoid_ax"},
    "geometry.ellipsoid_by_mm": {"geometry.params.ellipsoid_by"},
    "geometry.ellipsoid_cz_mm": {"geometry.params.ellipsoid_cz"},
    "geometry.elltube_ax_mm": {"geometry.params.elltube_ax"},
    "geometry.elltube_by_mm": {"geometry.params.elltube_by"},
    "geometry.elltube_hz_mm": {"geometry.params.elltube_hz"},
    "geometry.polyhedra_sides": {"geometry.params.polyhedra_nsides"},
    "geometry.tilt_x_deg": {"geometry.params.tilt_x"},
    "geometry.tilt_y_deg": {"geometry.params.tilt_y"},
}


GEOMETRY_STRUCTURE_ALIASES = {
    "nest": ("nest_box_box", "nest_box_tubs", "stack_in_box", "shell_nested"),
    "grid": ("grid_modules",),
    "ring": ("ring_modules",),
    "stack": ("stack_in_box",),
    "shell": ("shell_nested",),
    "box_tubs": ("nest_box_tubs",),
    "box_box": ("nest_box_box",),
    "box": ("single_box",),
    "cube": ("single_box",),
    "single_box": ("single_box",),
    "tubs": ("single_tubs",),
    "cylinder": ("single_tubs",),
    "single_tubs": ("single_tubs",),
    "sphere": ("single_sphere",),
    "single_sphere": ("single_sphere",),
    "orb": ("single_orb",),
    "single_orb": ("single_orb",),
    "cons": ("single_cons",),
    "single_cons": ("single_cons",),
    "trd": ("single_trd",),
    "single_trd": ("single_trd",),
    "polycone": ("single_polycone",),
    "single_polycone": ("single_polycone",),
    "cuttubs": ("single_cuttubs",),
    "single_cuttubs": ("single_cuttubs",),
    "boolean": ("boolean_union_boxes",),
    "boolean_union": ("boolean_union_boxes",),
    "boolean_subtraction": ("boolean_subtraction_boxes",),
    "boolean_intersection": ("boolean_intersection_boxes",),
    "tilted_box": ("tilted_box_in_parent",),
    "tilted_box_in_parent": ("tilted_box_in_parent",),
}
