from __future__ import annotations

EMPTY_GEOMETRY_FAMILY = {
    "allowed_paths": set(),
    "required_paths": set(),
    "name_binding_rules": [],
}


GEOMETRY_FAMILY_REGISTRY: dict[str, dict] = {
    "single_box": {
        "allowed_paths": {
            "geometry.params.module_x",
            "geometry.params.module_y",
            "geometry.params.module_z",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {
            "geometry.params.module_x",
            "geometry.params.module_y",
            "geometry.params.module_z",
        },
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "single_tubs": {
        "allowed_paths": {
            "geometry.params.child_rmax",
            "geometry.params.child_hz",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {"geometry.params.child_rmax", "geometry.params.child_hz"},
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "single_sphere": {
        "allowed_paths": {
            "geometry.params.child_rmax",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {"geometry.params.child_rmax"},
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "single_orb": {
        "allowed_paths": {
            "geometry.params.child_rmax",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {"geometry.params.child_rmax"},
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "single_cons": {
        "allowed_paths": {
            "geometry.params.rmax1",
            "geometry.params.rmax2",
            "geometry.params.child_hz",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {"geometry.params.rmax1", "geometry.params.rmax2", "geometry.params.child_hz"},
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "single_trd": {
        "allowed_paths": {
            "geometry.params.x1",
            "geometry.params.x2",
            "geometry.params.y1",
            "geometry.params.y2",
            "geometry.params.module_z",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {
            "geometry.params.x1",
            "geometry.params.x2",
            "geometry.params.y1",
            "geometry.params.y2",
            "geometry.params.module_z",
        },
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "single_polycone": {
        "allowed_paths": {
            "geometry.params.z1",
            "geometry.params.z2",
            "geometry.params.z3",
            "geometry.params.r1",
            "geometry.params.r2",
            "geometry.params.r3",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {
            "geometry.params.z1",
            "geometry.params.z2",
            "geometry.params.z3",
            "geometry.params.r1",
            "geometry.params.r2",
            "geometry.params.r3",
        },
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "single_cuttubs": {
        "allowed_paths": {
            "geometry.params.child_rmax",
            "geometry.params.child_hz",
            "geometry.params.tilt_x",
            "geometry.params.tilt_y",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {
            "geometry.params.child_rmax",
            "geometry.params.child_hz",
            "geometry.params.tilt_x",
            "geometry.params.tilt_y",
        },
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "single_trap": {
        "allowed_paths": {
            "geometry.params.trap_x1",
            "geometry.params.trap_x2",
            "geometry.params.trap_x3",
            "geometry.params.trap_x4",
            "geometry.params.trap_y1",
            "geometry.params.trap_y2",
            "geometry.params.trap_z",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {
            "geometry.params.trap_x1",
            "geometry.params.trap_x2",
            "geometry.params.trap_x3",
            "geometry.params.trap_x4",
            "geometry.params.trap_y1",
            "geometry.params.trap_y2",
            "geometry.params.trap_z",
        },
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "single_para": {
        "allowed_paths": {
            "geometry.params.para_x",
            "geometry.params.para_y",
            "geometry.params.para_z",
            "geometry.params.para_alpha",
            "geometry.params.para_theta",
            "geometry.params.para_phi",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {
            "geometry.params.para_x",
            "geometry.params.para_y",
            "geometry.params.para_z",
        },
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "single_torus": {
        "allowed_paths": {
            "geometry.params.torus_rtor",
            "geometry.params.torus_rmax",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {"geometry.params.torus_rtor", "geometry.params.torus_rmax"},
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "single_ellipsoid": {
        "allowed_paths": {
            "geometry.params.ellipsoid_ax",
            "geometry.params.ellipsoid_by",
            "geometry.params.ellipsoid_cz",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {
            "geometry.params.ellipsoid_ax",
            "geometry.params.ellipsoid_by",
            "geometry.params.ellipsoid_cz",
        },
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "single_elltube": {
        "allowed_paths": {
            "geometry.params.elltube_ax",
            "geometry.params.elltube_by",
            "geometry.params.elltube_hz",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {
            "geometry.params.elltube_ax",
            "geometry.params.elltube_by",
            "geometry.params.elltube_hz",
        },
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "single_polyhedra": {
        "allowed_paths": {
            "geometry.params.polyhedra_nsides",
            "geometry.params.z1",
            "geometry.params.z2",
            "geometry.params.z3",
            "geometry.params.r1",
            "geometry.params.r2",
            "geometry.params.r3",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {
            "geometry.params.polyhedra_nsides",
            "geometry.params.z1",
            "geometry.params.z2",
            "geometry.params.z3",
            "geometry.params.r1",
            "geometry.params.r2",
            "geometry.params.r3",
        },
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "boolean": {
        "allowed_paths": {
            "geometry.params.bool_a_x",
            "geometry.params.bool_a_y",
            "geometry.params.bool_a_z",
            "geometry.params.bool_b_x",
            "geometry.params.bool_b_y",
            "geometry.params.bool_b_z",
            "geometry.params.tx",
            "geometry.params.ty",
            "geometry.params.tz",
            "geometry.params.rx",
            "geometry.params.ry",
            "geometry.params.rz",
        },
        "required_paths": {
            "geometry.params.bool_a_x",
            "geometry.params.bool_a_y",
            "geometry.params.bool_a_z",
            "geometry.params.bool_b_x",
            "geometry.params.bool_b_y",
            "geometry.params.bool_b_z",
        },
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "ring": {
        "allowed_paths": {
            "geometry.params.module_x",
            "geometry.params.module_y",
            "geometry.params.module_z",
            "geometry.params.n",
            "geometry.params.radius",
            "geometry.params.clearance",
        },
        "required_paths": {"geometry.graph_program"},
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "grid": {
        "allowed_paths": {
            "geometry.params.module_x",
            "geometry.params.module_y",
            "geometry.params.module_z",
            "geometry.params.nx",
            "geometry.params.ny",
            "geometry.params.pitch_x",
            "geometry.params.pitch_y",
            "geometry.params.clearance",
        },
        "required_paths": {"geometry.graph_program"},
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "nest": {
        "allowed_paths": {
            "geometry.params.parent_x",
            "geometry.params.parent_y",
            "geometry.params.parent_z",
            "geometry.params.child_rmax",
            "geometry.params.child_hz",
            "geometry.params.clearance",
        },
        "required_paths": {"geometry.graph_program"},
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "stack": {
        "allowed_paths": {
            "geometry.params.stack_x",
            "geometry.params.stack_y",
            "geometry.params.t1",
            "geometry.params.t2",
            "geometry.params.t3",
            "geometry.params.stack_clearance",
            "geometry.params.parent_x",
            "geometry.params.parent_y",
            "geometry.params.parent_z",
            "geometry.params.nest_clearance",
        },
        "required_paths": {"geometry.graph_program"},
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
    "shell": {
        "allowed_paths": {
            "geometry.params.inner_r",
            "geometry.params.th1",
            "geometry.params.th2",
            "geometry.params.th3",
            "geometry.params.hz",
            "geometry.params.child_rmax",
            "geometry.params.child_hz",
            "geometry.params.clearance",
        },
        "required_paths": {"geometry.graph_program"},
        "name_binding_rules": [{"volume_material_must_match_root": True}],
    },
}


def get_geometry_family(structure: str | None) -> dict:
    if not structure:
        return EMPTY_GEOMETRY_FAMILY
    return GEOMETRY_FAMILY_REGISTRY.get(structure, EMPTY_GEOMETRY_FAMILY)
